### ISSUE TITLE
Cannot access Pierre Bréjoux's info panel (JoP)

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#95] opened 2020-12-01 01:09 UTC
I cannot access Pierre Bréjoux's info panel when I click on his dot on the JoP map. If I click on his name in a cluster, I also cannot activate a different cluster by clicking on it afterward, the app locks up.  

- [trello card](https://trello.com/c/TLDNGtcT/12-pierre-br%C3%A9joux)
- [map cluster with Bréjoux in it](https://intert-wine-leigh-akwemh35fa-uc.a.run.app/map/jop/cluster/48.8680,2.4150/9/TLD.62t)

I think he is the only subject with no feature image associated with him, I don't know if that is a factor in this bug. If there's no image, the feature image is supposed to have a filler icon of the subject type in its place (if this isn't coded in already, let me know, I'll dig up the mock-up. We started with the filler images as the design before adding the real content).

**Comment by jrmerz** [comment] 2020-12-01 17:37
While the app needs to handle this error better, it seems to be a data issue.  @qjhart the creator field for this person looks like: `["URL","Source name"]`

**Comment by qjhart** [comment] 2020-12-03 01:04
The data part of this is non-reproducable, but looks like an older trello card had 

* Source Name
  *  URL 

as a placeholder.

This is no longer a problem.

**Comment by jrmerz** [comment] 2020-12-03 16:38
This app now matches the card as far as I can tell, moving to QA/QC

**Closed as completed** 2020-12-03 16:52 UTC
Labels: bug
